require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AivdsController do

  # This should return the minimal set of attributes required to create a valid
  # Aivd. As you add validations to Aivd, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AivdsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all aivds as @aivds" do
      aivd = Aivd.create! valid_attributes
      get :index, {}, valid_session
      assigns(:aivds).should eq([aivd])
    end
  end

  describe "GET show" do
    it "assigns the requested aivd as @aivd" do
      aivd = Aivd.create! valid_attributes
      get :show, {:id => aivd.to_param}, valid_session
      assigns(:aivd).should eq(aivd)
    end
  end

  describe "GET new" do
    it "assigns a new aivd as @aivd" do
      get :new, {}, valid_session
      assigns(:aivd).should be_a_new(Aivd)
    end
  end

  describe "GET edit" do
    it "assigns the requested aivd as @aivd" do
      aivd = Aivd.create! valid_attributes
      get :edit, {:id => aivd.to_param}, valid_session
      assigns(:aivd).should eq(aivd)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Aivd" do
        expect {
          post :create, {:aivd => valid_attributes}, valid_session
        }.to change(Aivd, :count).by(1)
      end

      it "assigns a newly created aivd as @aivd" do
        post :create, {:aivd => valid_attributes}, valid_session
        assigns(:aivd).should be_a(Aivd)
        assigns(:aivd).should be_persisted
      end

      it "redirects to the created aivd" do
        post :create, {:aivd => valid_attributes}, valid_session
        response.should redirect_to(Aivd.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved aivd as @aivd" do
        # Trigger the behavior that occurs when invalid params are submitted
        Aivd.any_instance.stub(:save).and_return(false)
        post :create, {:aivd => {}}, valid_session
        assigns(:aivd).should be_a_new(Aivd)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Aivd.any_instance.stub(:save).and_return(false)
        post :create, {:aivd => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested aivd" do
        aivd = Aivd.create! valid_attributes
        # Assuming there are no other aivds in the database, this
        # specifies that the Aivd created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Aivd.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => aivd.to_param, :aivd => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested aivd as @aivd" do
        aivd = Aivd.create! valid_attributes
        put :update, {:id => aivd.to_param, :aivd => valid_attributes}, valid_session
        assigns(:aivd).should eq(aivd)
      end

      it "redirects to the aivd" do
        aivd = Aivd.create! valid_attributes
        put :update, {:id => aivd.to_param, :aivd => valid_attributes}, valid_session
        response.should redirect_to(aivd)
      end
    end

    describe "with invalid params" do
      it "assigns the aivd as @aivd" do
        aivd = Aivd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Aivd.any_instance.stub(:save).and_return(false)
        put :update, {:id => aivd.to_param, :aivd => {}}, valid_session
        assigns(:aivd).should eq(aivd)
      end

      it "re-renders the 'edit' template" do
        aivd = Aivd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Aivd.any_instance.stub(:save).and_return(false)
        put :update, {:id => aivd.to_param, :aivd => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested aivd" do
      aivd = Aivd.create! valid_attributes
      expect {
        delete :destroy, {:id => aivd.to_param}, valid_session
      }.to change(Aivd, :count).by(-1)
    end

    it "redirects to the aivds list" do
      aivd = Aivd.create! valid_attributes
      delete :destroy, {:id => aivd.to_param}, valid_session
      response.should redirect_to(aivds_url)
    end
  end

end
