require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AtendimentoReportsController do

  # This should return the minimal set of attributes required to create a valid
  # AtendimentoReport. As you add validations to AtendimentoReport, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AtendimentoReportsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all atendimento_reports as @atendimento_reports" do
      atendimento_report = AtendimentoReport.create! valid_attributes
      get :index, {}, valid_session
      assigns(:atendimento_reports).should eq([atendimento_report])
    end
  end

  describe "GET show" do
    it "assigns the requested atendimento_report as @atendimento_report" do
      atendimento_report = AtendimentoReport.create! valid_attributes
      get :show, {:id => atendimento_report.to_param}, valid_session
      assigns(:atendimento_report).should eq(atendimento_report)
    end
  end

  describe "GET new" do
    it "assigns a new atendimento_report as @atendimento_report" do
      get :new, {}, valid_session
      assigns(:atendimento_report).should be_a_new(AtendimentoReport)
    end
  end

  describe "GET edit" do
    it "assigns the requested atendimento_report as @atendimento_report" do
      atendimento_report = AtendimentoReport.create! valid_attributes
      get :edit, {:id => atendimento_report.to_param}, valid_session
      assigns(:atendimento_report).should eq(atendimento_report)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AtendimentoReport" do
        expect {
          post :create, {:atendimento_report => valid_attributes}, valid_session
        }.to change(AtendimentoReport, :count).by(1)
      end

      it "assigns a newly created atendimento_report as @atendimento_report" do
        post :create, {:atendimento_report => valid_attributes}, valid_session
        assigns(:atendimento_report).should be_a(AtendimentoReport)
        assigns(:atendimento_report).should be_persisted
      end

      it "redirects to the created atendimento_report" do
        post :create, {:atendimento_report => valid_attributes}, valid_session
        response.should redirect_to(AtendimentoReport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved atendimento_report as @atendimento_report" do
        # Trigger the behavior that occurs when invalid params are submitted
        AtendimentoReport.any_instance.stub(:save).and_return(false)
        post :create, {:atendimento_report => {}}, valid_session
        assigns(:atendimento_report).should be_a_new(AtendimentoReport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AtendimentoReport.any_instance.stub(:save).and_return(false)
        post :create, {:atendimento_report => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested atendimento_report" do
        atendimento_report = AtendimentoReport.create! valid_attributes
        # Assuming there are no other atendimento_reports in the database, this
        # specifies that the AtendimentoReport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AtendimentoReport.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => atendimento_report.to_param, :atendimento_report => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested atendimento_report as @atendimento_report" do
        atendimento_report = AtendimentoReport.create! valid_attributes
        put :update, {:id => atendimento_report.to_param, :atendimento_report => valid_attributes}, valid_session
        assigns(:atendimento_report).should eq(atendimento_report)
      end

      it "redirects to the atendimento_report" do
        atendimento_report = AtendimentoReport.create! valid_attributes
        put :update, {:id => atendimento_report.to_param, :atendimento_report => valid_attributes}, valid_session
        response.should redirect_to(atendimento_report)
      end
    end

    describe "with invalid params" do
      it "assigns the atendimento_report as @atendimento_report" do
        atendimento_report = AtendimentoReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AtendimentoReport.any_instance.stub(:save).and_return(false)
        put :update, {:id => atendimento_report.to_param, :atendimento_report => {}}, valid_session
        assigns(:atendimento_report).should eq(atendimento_report)
      end

      it "re-renders the 'edit' template" do
        atendimento_report = AtendimentoReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AtendimentoReport.any_instance.stub(:save).and_return(false)
        put :update, {:id => atendimento_report.to_param, :atendimento_report => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested atendimento_report" do
      atendimento_report = AtendimentoReport.create! valid_attributes
      expect {
        delete :destroy, {:id => atendimento_report.to_param}, valid_session
      }.to change(AtendimentoReport, :count).by(-1)
    end

    it "redirects to the atendimento_reports list" do
      atendimento_report = AtendimentoReport.create! valid_attributes
      delete :destroy, {:id => atendimento_report.to_param}, valid_session
      response.should redirect_to(atendimento_reports_url)
    end
  end

end
