require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AvdsController do

  # This should return the minimal set of attributes required to create a valid
  # Avd. As you add validations to Avd, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AvdsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all avds as @avds" do
      avd = Avd.create! valid_attributes
      get :index, {}, valid_session
      assigns(:avds).should eq([avd])
    end
  end

  describe "GET show" do
    it "assigns the requested avd as @avd" do
      avd = Avd.create! valid_attributes
      get :show, {:id => avd.to_param}, valid_session
      assigns(:avd).should eq(avd)
    end
  end

  describe "GET new" do
    it "assigns a new avd as @avd" do
      get :new, {}, valid_session
      assigns(:avd).should be_a_new(Avd)
    end
  end

  describe "GET edit" do
    it "assigns the requested avd as @avd" do
      avd = Avd.create! valid_attributes
      get :edit, {:id => avd.to_param}, valid_session
      assigns(:avd).should eq(avd)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Avd" do
        expect {
          post :create, {:avd => valid_attributes}, valid_session
        }.to change(Avd, :count).by(1)
      end

      it "assigns a newly created avd as @avd" do
        post :create, {:avd => valid_attributes}, valid_session
        assigns(:avd).should be_a(Avd)
        assigns(:avd).should be_persisted
      end

      it "redirects to the created avd" do
        post :create, {:avd => valid_attributes}, valid_session
        response.should redirect_to(Avd.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved avd as @avd" do
        # Trigger the behavior that occurs when invalid params are submitted
        Avd.any_instance.stub(:save).and_return(false)
        post :create, {:avd => {}}, valid_session
        assigns(:avd).should be_a_new(Avd)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Avd.any_instance.stub(:save).and_return(false)
        post :create, {:avd => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested avd" do
        avd = Avd.create! valid_attributes
        # Assuming there are no other avds in the database, this
        # specifies that the Avd created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Avd.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => avd.to_param, :avd => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested avd as @avd" do
        avd = Avd.create! valid_attributes
        put :update, {:id => avd.to_param, :avd => valid_attributes}, valid_session
        assigns(:avd).should eq(avd)
      end

      it "redirects to the avd" do
        avd = Avd.create! valid_attributes
        put :update, {:id => avd.to_param, :avd => valid_attributes}, valid_session
        response.should redirect_to(avd)
      end
    end

    describe "with invalid params" do
      it "assigns the avd as @avd" do
        avd = Avd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Avd.any_instance.stub(:save).and_return(false)
        put :update, {:id => avd.to_param, :avd => {}}, valid_session
        assigns(:avd).should eq(avd)
      end

      it "re-renders the 'edit' template" do
        avd = Avd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Avd.any_instance.stub(:save).and_return(false)
        put :update, {:id => avd.to_param, :avd => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested avd" do
      avd = Avd.create! valid_attributes
      expect {
        delete :destroy, {:id => avd.to_param}, valid_session
      }.to change(Avd, :count).by(-1)
    end

    it "redirects to the avds list" do
      avd = Avd.create! valid_attributes
      delete :destroy, {:id => avd.to_param}, valid_session
      response.should redirect_to(avds_url)
    end
  end

end
