require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExameComplementarsController do

  # This should return the minimal set of attributes required to create a valid
  # ExameComplementar. As you add validations to ExameComplementar, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExameComplementarsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all exame_complementars as @exame_complementars" do
      exame_complementar = ExameComplementar.create! valid_attributes
      get :index, {}, valid_session
      assigns(:exame_complementars).should eq([exame_complementar])
    end
  end

  describe "GET show" do
    it "assigns the requested exame_complementar as @exame_complementar" do
      exame_complementar = ExameComplementar.create! valid_attributes
      get :show, {:id => exame_complementar.to_param}, valid_session
      assigns(:exame_complementar).should eq(exame_complementar)
    end
  end

  describe "GET new" do
    it "assigns a new exame_complementar as @exame_complementar" do
      get :new, {}, valid_session
      assigns(:exame_complementar).should be_a_new(ExameComplementar)
    end
  end

  describe "GET edit" do
    it "assigns the requested exame_complementar as @exame_complementar" do
      exame_complementar = ExameComplementar.create! valid_attributes
      get :edit, {:id => exame_complementar.to_param}, valid_session
      assigns(:exame_complementar).should eq(exame_complementar)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExameComplementar" do
        expect {
          post :create, {:exame_complementar => valid_attributes}, valid_session
        }.to change(ExameComplementar, :count).by(1)
      end

      it "assigns a newly created exame_complementar as @exame_complementar" do
        post :create, {:exame_complementar => valid_attributes}, valid_session
        assigns(:exame_complementar).should be_a(ExameComplementar)
        assigns(:exame_complementar).should be_persisted
      end

      it "redirects to the created exame_complementar" do
        post :create, {:exame_complementar => valid_attributes}, valid_session
        response.should redirect_to(ExameComplementar.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exame_complementar as @exame_complementar" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExameComplementar.any_instance.stub(:save).and_return(false)
        post :create, {:exame_complementar => {}}, valid_session
        assigns(:exame_complementar).should be_a_new(ExameComplementar)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExameComplementar.any_instance.stub(:save).and_return(false)
        post :create, {:exame_complementar => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exame_complementar" do
        exame_complementar = ExameComplementar.create! valid_attributes
        # Assuming there are no other exame_complementars in the database, this
        # specifies that the ExameComplementar created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExameComplementar.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => exame_complementar.to_param, :exame_complementar => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested exame_complementar as @exame_complementar" do
        exame_complementar = ExameComplementar.create! valid_attributes
        put :update, {:id => exame_complementar.to_param, :exame_complementar => valid_attributes}, valid_session
        assigns(:exame_complementar).should eq(exame_complementar)
      end

      it "redirects to the exame_complementar" do
        exame_complementar = ExameComplementar.create! valid_attributes
        put :update, {:id => exame_complementar.to_param, :exame_complementar => valid_attributes}, valid_session
        response.should redirect_to(exame_complementar)
      end
    end

    describe "with invalid params" do
      it "assigns the exame_complementar as @exame_complementar" do
        exame_complementar = ExameComplementar.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExameComplementar.any_instance.stub(:save).and_return(false)
        put :update, {:id => exame_complementar.to_param, :exame_complementar => {}}, valid_session
        assigns(:exame_complementar).should eq(exame_complementar)
      end

      it "re-renders the 'edit' template" do
        exame_complementar = ExameComplementar.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExameComplementar.any_instance.stub(:save).and_return(false)
        put :update, {:id => exame_complementar.to_param, :exame_complementar => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exame_complementar" do
      exame_complementar = ExameComplementar.create! valid_attributes
      expect {
        delete :destroy, {:id => exame_complementar.to_param}, valid_session
      }.to change(ExameComplementar, :count).by(-1)
    end

    it "redirects to the exame_complementars list" do
      exame_complementar = ExameComplementar.create! valid_attributes
      delete :destroy, {:id => exame_complementar.to_param}, valid_session
      response.should redirect_to(exame_complementars_url)
    end
  end

end
