require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PacienteReportsController do

  # This should return the minimal set of attributes required to create a valid
  # PacienteReport. As you add validations to PacienteReport, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PacienteReportsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all paciente_reports as @paciente_reports" do
      paciente_report = PacienteReport.create! valid_attributes
      get :index, {}, valid_session
      assigns(:paciente_reports).should eq([paciente_report])
    end
  end

  describe "GET show" do
    it "assigns the requested paciente_report as @paciente_report" do
      paciente_report = PacienteReport.create! valid_attributes
      get :show, {:id => paciente_report.to_param}, valid_session
      assigns(:paciente_report).should eq(paciente_report)
    end
  end

  describe "GET new" do
    it "assigns a new paciente_report as @paciente_report" do
      get :new, {}, valid_session
      assigns(:paciente_report).should be_a_new(PacienteReport)
    end
  end

  describe "GET edit" do
    it "assigns the requested paciente_report as @paciente_report" do
      paciente_report = PacienteReport.create! valid_attributes
      get :edit, {:id => paciente_report.to_param}, valid_session
      assigns(:paciente_report).should eq(paciente_report)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PacienteReport" do
        expect {
          post :create, {:paciente_report => valid_attributes}, valid_session
        }.to change(PacienteReport, :count).by(1)
      end

      it "assigns a newly created paciente_report as @paciente_report" do
        post :create, {:paciente_report => valid_attributes}, valid_session
        assigns(:paciente_report).should be_a(PacienteReport)
        assigns(:paciente_report).should be_persisted
      end

      it "redirects to the created paciente_report" do
        post :create, {:paciente_report => valid_attributes}, valid_session
        response.should redirect_to(PacienteReport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved paciente_report as @paciente_report" do
        # Trigger the behavior that occurs when invalid params are submitted
        PacienteReport.any_instance.stub(:save).and_return(false)
        post :create, {:paciente_report => {}}, valid_session
        assigns(:paciente_report).should be_a_new(PacienteReport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PacienteReport.any_instance.stub(:save).and_return(false)
        post :create, {:paciente_report => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested paciente_report" do
        paciente_report = PacienteReport.create! valid_attributes
        # Assuming there are no other paciente_reports in the database, this
        # specifies that the PacienteReport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PacienteReport.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => paciente_report.to_param, :paciente_report => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested paciente_report as @paciente_report" do
        paciente_report = PacienteReport.create! valid_attributes
        put :update, {:id => paciente_report.to_param, :paciente_report => valid_attributes}, valid_session
        assigns(:paciente_report).should eq(paciente_report)
      end

      it "redirects to the paciente_report" do
        paciente_report = PacienteReport.create! valid_attributes
        put :update, {:id => paciente_report.to_param, :paciente_report => valid_attributes}, valid_session
        response.should redirect_to(paciente_report)
      end
    end

    describe "with invalid params" do
      it "assigns the paciente_report as @paciente_report" do
        paciente_report = PacienteReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PacienteReport.any_instance.stub(:save).and_return(false)
        put :update, {:id => paciente_report.to_param, :paciente_report => {}}, valid_session
        assigns(:paciente_report).should eq(paciente_report)
      end

      it "re-renders the 'edit' template" do
        paciente_report = PacienteReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PacienteReport.any_instance.stub(:save).and_return(false)
        put :update, {:id => paciente_report.to_param, :paciente_report => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested paciente_report" do
      paciente_report = PacienteReport.create! valid_attributes
      expect {
        delete :destroy, {:id => paciente_report.to_param}, valid_session
      }.to change(PacienteReport, :count).by(-1)
    end

    it "redirects to the paciente_reports list" do
      paciente_report = PacienteReport.create! valid_attributes
      delete :destroy, {:id => paciente_report.to_param}, valid_session
      response.should redirect_to(paciente_reports_url)
    end
  end

end
