require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RelogiosController do

  # This should return the minimal set of attributes required to create a valid
  # Relogio. As you add validations to Relogio, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RelogiosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all relogios as @relogios" do
      relogio = Relogio.create! valid_attributes
      get :index, {}, valid_session
      assigns(:relogios).should eq([relogio])
    end
  end

  describe "GET show" do
    it "assigns the requested relogio as @relogio" do
      relogio = Relogio.create! valid_attributes
      get :show, {:id => relogio.to_param}, valid_session
      assigns(:relogio).should eq(relogio)
    end
  end

  describe "GET new" do
    it "assigns a new relogio as @relogio" do
      get :new, {}, valid_session
      assigns(:relogio).should be_a_new(Relogio)
    end
  end

  describe "GET edit" do
    it "assigns the requested relogio as @relogio" do
      relogio = Relogio.create! valid_attributes
      get :edit, {:id => relogio.to_param}, valid_session
      assigns(:relogio).should eq(relogio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Relogio" do
        expect {
          post :create, {:relogio => valid_attributes}, valid_session
        }.to change(Relogio, :count).by(1)
      end

      it "assigns a newly created relogio as @relogio" do
        post :create, {:relogio => valid_attributes}, valid_session
        assigns(:relogio).should be_a(Relogio)
        assigns(:relogio).should be_persisted
      end

      it "redirects to the created relogio" do
        post :create, {:relogio => valid_attributes}, valid_session
        response.should redirect_to(Relogio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved relogio as @relogio" do
        # Trigger the behavior that occurs when invalid params are submitted
        Relogio.any_instance.stub(:save).and_return(false)
        post :create, {:relogio => {}}, valid_session
        assigns(:relogio).should be_a_new(Relogio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Relogio.any_instance.stub(:save).and_return(false)
        post :create, {:relogio => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested relogio" do
        relogio = Relogio.create! valid_attributes
        # Assuming there are no other relogios in the database, this
        # specifies that the Relogio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Relogio.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => relogio.to_param, :relogio => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested relogio as @relogio" do
        relogio = Relogio.create! valid_attributes
        put :update, {:id => relogio.to_param, :relogio => valid_attributes}, valid_session
        assigns(:relogio).should eq(relogio)
      end

      it "redirects to the relogio" do
        relogio = Relogio.create! valid_attributes
        put :update, {:id => relogio.to_param, :relogio => valid_attributes}, valid_session
        response.should redirect_to(relogio)
      end
    end

    describe "with invalid params" do
      it "assigns the relogio as @relogio" do
        relogio = Relogio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Relogio.any_instance.stub(:save).and_return(false)
        put :update, {:id => relogio.to_param, :relogio => {}}, valid_session
        assigns(:relogio).should eq(relogio)
      end

      it "re-renders the 'edit' template" do
        relogio = Relogio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Relogio.any_instance.stub(:save).and_return(false)
        put :update, {:id => relogio.to_param, :relogio => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested relogio" do
      relogio = Relogio.create! valid_attributes
      expect {
        delete :destroy, {:id => relogio.to_param}, valid_session
      }.to change(Relogio, :count).by(-1)
    end

    it "redirects to the relogios list" do
      relogio = Relogio.create! valid_attributes
      delete :destroy, {:id => relogio.to_param}, valid_session
      response.should redirect_to(relogios_url)
    end
  end

end
